### ISSUE TITLE
Determine heart rate

### ISSUE THREAD

**Issue by iuga-paula** [SmartSleepIoT/SmartSleepCoding#13]
Story points: 0.5 
Just read a senzor

**Comment by iuga-paula** [comment]
![image](https://user-images.githubusercontent.com/61518083/144852132-b2f62fb3-abfd-4561-87c8-815f87903bdc.png)
folosind un fisier extern din care se citesc datele la senzor

**Comment by iuga-paula** [comment]
depilcated issue #15

**Comment by iuga-paula** [comment]
when finished please done also #35 - set and send sensor data to endpoint

**Comment by mirastroie** [comment]
Done here https://github.com/SmartSleepIoT/SmartSleepCoding/commit/d4f46191d0b7b255387072f8cf5681f78b6c42ea
