### ISSUE TITLE
Determine breaths

### ISSUE THREAD

**Issue by iuga-paula** [SmartSleepIoT/SmartSleepCoding#14]

**Comment by iuga-paula** [comment]
![image](https://user-images.githubusercontent.com/61518083/144853493-05769267-8f9f-4eff-9f8e-21c3a928b885.png)

folosind un fisier extern din care se citesc datele la senzor

**Comment by iuga-paula** [comment]
when finished please done also  #35 - set and send sensor data to endpoint

**Comment by NedelcuRadu** [comment]
Determined as being unecessary in 7 Dec meeting
