### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by iuga-paula** [SmartSleepIoT/SmartSleepCoding#20]
Units tests & test  error documentation

**Comment by NedelcuRadu** [comment]
Added tests for /auth functions and /temp, /waking_mode, /pillow_angle, /wake_up_hour endpoints

**Comment by iuga-paula** [comment]
[Unit tests report document](https://docs.google.com/document/d/1Ebwm3IryhBhyDkCVhmeJv-OtdnAs0xz_rU-RxpFCZOI/edit)

**Comment by iuga-paula** [comment]
> coverage run -m pytest
> coverage report
> coverage html  # open htmlcov/index.html in a browser

**Comment by iuga-paula** [comment]
![image](https://user-images.githubusercontent.com/61518083/151980249-42685ce4-5a47-4418-b406-aed1827d9e23.png)

**Comment by DianaVasiliu** [comment]
Fixed #70
