### ISSUE TITLE
Emit sounds, vibrations, lights for waking up

### ISSUE THREAD

**Issue by mirastroie** [SmartSleepIoT/SmartSleepCoding#9]
Emit sounds, vibrations, lights to wake the user up.

**Comment by iuga-paula** [comment]
[issue done](https://github.com/SmartSleepIoT/SmartSleepCoding/commit/d05051193da5c01b572f895dda1cb9fa26a53942)

**Comment by iuga-paula** [comment]
Bug when resetting the wake-up data - also refactoring needed to be done.

**Comment by iuga-paula** [comment]
[issue done](https://github.com/SmartSleepIoT/SmartSleepCoding/pull/24)
